version: 2

models:
  - name: stg_locations
    columns:
      - name: location_id
        tests:
          - unique
          - not_null
      - name: latitude
        tests:
          - not_null
      - name: longitude
        tests:
          - not_null

  - name: stg_weather_readings
    columns:
      - name: location_id
        tests:
          - not_null
      - name: temperature
        tests:
          - not_null